// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.14.0
// source: client-namenode.proto

package proto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type GetFileBlocksLocationRequestProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FilePath string `protobuf:"bytes,1,opt,name=FilePath,proto3" json:"FilePath,omitempty"`
}

func (x *GetFileBlocksLocationRequestProto) Reset() {
	*x = GetFileBlocksLocationRequestProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_namenode_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFileBlocksLocationRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileBlocksLocationRequestProto) ProtoMessage() {}

func (x *GetFileBlocksLocationRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_client_namenode_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileBlocksLocationRequestProto.ProtoReflect.Descriptor instead.
func (*GetFileBlocksLocationRequestProto) Descriptor() ([]byte, []int) {
	return file_client_namenode_proto_rawDescGZIP(), []int{0}
}

func (x *GetFileBlocksLocationRequestProto) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

// BlockIP is the IP of block
type BlockInfoProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FilePathInFS    string `protobuf:"bytes,1,opt,name=FilePathInFS,proto3" json:"FilePathInFS,omitempty"`
	BlockIndex      uint32 `protobuf:"varint,2,opt,name=BlockIndex,proto3" json:"BlockIndex,omitempty"`
	LastBlockInFile bool   `protobuf:"varint,3,opt,name=LastBlockInFile,proto3" json:"LastBlockInFile,omitempty"`
	BlockIP         string `protobuf:"bytes,4,opt,name=BlockIP,proto3" json:"BlockIP,omitempty"`
}

func (x *BlockInfoProto) Reset() {
	*x = BlockInfoProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_namenode_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlockInfoProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockInfoProto) ProtoMessage() {}

func (x *BlockInfoProto) ProtoReflect() protoreflect.Message {
	mi := &file_client_namenode_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockInfoProto.ProtoReflect.Descriptor instead.
func (*BlockInfoProto) Descriptor() ([]byte, []int) {
	return file_client_namenode_proto_rawDescGZIP(), []int{1}
}

func (x *BlockInfoProto) GetFilePathInFS() string {
	if x != nil {
		return x.FilePathInFS
	}
	return ""
}

func (x *BlockInfoProto) GetBlockIndex() uint32 {
	if x != nil {
		return x.BlockIndex
	}
	return 0
}

func (x *BlockInfoProto) GetLastBlockInFile() bool {
	if x != nil {
		return x.LastBlockInFile
	}
	return false
}

func (x *BlockInfoProto) GetBlockIP() string {
	if x != nil {
		return x.BlockIP
	}
	return ""
}

type GetFileBlocksLocationResponseProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Blocks []*BlockInfoProto `protobuf:"bytes,1,rep,name=Blocks,proto3" json:"Blocks,omitempty"`
}

func (x *GetFileBlocksLocationResponseProto) Reset() {
	*x = GetFileBlocksLocationResponseProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_namenode_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFileBlocksLocationResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileBlocksLocationResponseProto) ProtoMessage() {}

func (x *GetFileBlocksLocationResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_client_namenode_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileBlocksLocationResponseProto.ProtoReflect.Descriptor instead.
func (*GetFileBlocksLocationResponseProto) Descriptor() ([]byte, []int) {
	return file_client_namenode_proto_rawDescGZIP(), []int{2}
}

func (x *GetFileBlocksLocationResponseProto) GetBlocks() []*BlockInfoProto {
	if x != nil {
		return x.Blocks
	}
	return nil
}

type CreateFileRequestProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FilePath string `protobuf:"bytes,1,opt,name=FilePath,proto3" json:"FilePath,omitempty"`
	BlockNum uint32 `protobuf:"varint,2,opt,name=BlockNum,proto3" json:"BlockNum,omitempty"`
}

func (x *CreateFileRequestProto) Reset() {
	*x = CreateFileRequestProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_namenode_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateFileRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFileRequestProto) ProtoMessage() {}

func (x *CreateFileRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_client_namenode_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFileRequestProto.ProtoReflect.Descriptor instead.
func (*CreateFileRequestProto) Descriptor() ([]byte, []int) {
	return file_client_namenode_proto_rawDescGZIP(), []int{3}
}

func (x *CreateFileRequestProto) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *CreateFileRequestProto) GetBlockNum() uint32 {
	if x != nil {
		return x.BlockNum
	}
	return 0
}

type CreateFileResponseProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=Result,proto3" json:"Result,omitempty"`
}

func (x *CreateFileResponseProto) Reset() {
	*x = CreateFileResponseProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_namenode_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateFileResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFileResponseProto) ProtoMessage() {}

func (x *CreateFileResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_client_namenode_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFileResponseProto.ProtoReflect.Descriptor instead.
func (*CreateFileResponseProto) Descriptor() ([]byte, []int) {
	return file_client_namenode_proto_rawDescGZIP(), []int{4}
}

func (x *CreateFileResponseProto) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type DeleteFileRequestProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FilePath string `protobuf:"bytes,1,opt,name=FilePath,proto3" json:"FilePath,omitempty"`
}

func (x *DeleteFileRequestProto) Reset() {
	*x = DeleteFileRequestProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_namenode_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteFileRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileRequestProto) ProtoMessage() {}

func (x *DeleteFileRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_client_namenode_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileRequestProto.ProtoReflect.Descriptor instead.
func (*DeleteFileRequestProto) Descriptor() ([]byte, []int) {
	return file_client_namenode_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteFileRequestProto) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

type DeleteFileResponseProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=Result,proto3" json:"Result,omitempty"`
}

func (x *DeleteFileResponseProto) Reset() {
	*x = DeleteFileResponseProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_namenode_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteFileResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileResponseProto) ProtoMessage() {}

func (x *DeleteFileResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_client_namenode_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileResponseProto.ProtoReflect.Descriptor instead.
func (*DeleteFileResponseProto) Descriptor() ([]byte, []int) {
	return file_client_namenode_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteFileResponseProto) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_client_namenode_proto protoreflect.FileDescriptor

var file_client_namenode_proto_rawDesc = []byte{
	0x0a, 0x15, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2d, 0x6e, 0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3f,
	0x0a, 0x21, 0x47, 0x65, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x4c,
	0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x46, 0x69, 0x6c, 0x65, 0x50, 0x61, 0x74, 0x68, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x46, 0x69, 0x6c, 0x65, 0x50, 0x61, 0x74, 0x68, 0x22,
	0x98, 0x01, 0x0a, 0x0e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x22, 0x0a, 0x0c, 0x46, 0x69, 0x6c, 0x65, 0x50, 0x61, 0x74, 0x68, 0x49, 0x6e,
	0x46, 0x53, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x46, 0x69, 0x6c, 0x65, 0x50, 0x61,
	0x74, 0x68, 0x49, 0x6e, 0x46, 0x53, 0x12, 0x1e, 0x0a, 0x0a, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x49,
	0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x42, 0x6c, 0x6f, 0x63,
	0x6b, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x28, 0x0a, 0x0f, 0x4c, 0x61, 0x73, 0x74, 0x42, 0x6c,
	0x6f, 0x63, 0x6b, 0x49, 0x6e, 0x46, 0x69, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x0f, 0x4c, 0x61, 0x73, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x6e, 0x46, 0x69, 0x6c, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x50, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x50, 0x22, 0x53, 0x0a, 0x22, 0x47, 0x65,
	0x74, 0x46, 0x69, 0x6c, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x4c, 0x6f, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x2d, 0x0a, 0x06, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x6e,
	0x66, 0x6f, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x06, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x22,
	0x50, 0x0a, 0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x46, 0x69, 0x6c,
	0x65, 0x50, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x46, 0x69, 0x6c,
	0x65, 0x50, 0x61, 0x74, 0x68, 0x12, 0x1a, 0x0a, 0x08, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x4e, 0x75,
	0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x4e, 0x75,
	0x6d, 0x22, 0x31, 0x0a, 0x17, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x16, 0x0a, 0x06,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x22, 0x34, 0x0a, 0x16, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x69,
	0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1a,
	0x0a, 0x08, 0x46, 0x69, 0x6c, 0x65, 0x50, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x46, 0x69, 0x6c, 0x65, 0x50, 0x61, 0x74, 0x68, 0x22, 0x31, 0x0a, 0x17, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_client_namenode_proto_rawDescOnce sync.Once
	file_client_namenode_proto_rawDescData = file_client_namenode_proto_rawDesc
)

func file_client_namenode_proto_rawDescGZIP() []byte {
	file_client_namenode_proto_rawDescOnce.Do(func() {
		file_client_namenode_proto_rawDescData = protoimpl.X.CompressGZIP(file_client_namenode_proto_rawDescData)
	})
	return file_client_namenode_proto_rawDescData
}

var file_client_namenode_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_client_namenode_proto_goTypes = []interface{}{
	(*GetFileBlocksLocationRequestProto)(nil),  // 0: proto.GetFileBlocksLocationRequestProto
	(*BlockInfoProto)(nil),                     // 1: proto.BlockInfoProto
	(*GetFileBlocksLocationResponseProto)(nil), // 2: proto.GetFileBlocksLocationResponseProto
	(*CreateFileRequestProto)(nil),             // 3: proto.CreateFileRequestProto
	(*CreateFileResponseProto)(nil),            // 4: proto.CreateFileResponseProto
	(*DeleteFileRequestProto)(nil),             // 5: proto.DeleteFileRequestProto
	(*DeleteFileResponseProto)(nil),            // 6: proto.DeleteFileResponseProto
}
var file_client_namenode_proto_depIdxs = []int32{
	1, // 0: proto.GetFileBlocksLocationResponseProto.Blocks:type_name -> proto.BlockInfoProto
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_client_namenode_proto_init() }
func file_client_namenode_proto_init() {
	if File_client_namenode_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_client_namenode_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFileBlocksLocationRequestProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_namenode_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlockInfoProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_namenode_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFileBlocksLocationResponseProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_namenode_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateFileRequestProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_namenode_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateFileResponseProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_namenode_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteFileRequestProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_namenode_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteFileResponseProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_client_namenode_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_client_namenode_proto_goTypes,
		DependencyIndexes: file_client_namenode_proto_depIdxs,
		MessageInfos:      file_client_namenode_proto_msgTypes,
	}.Build()
	File_client_namenode_proto = out.File
	file_client_namenode_proto_rawDesc = nil
	file_client_namenode_proto_goTypes = nil
	file_client_namenode_proto_depIdxs = nil
}
